#!/usr/bin/env python3
"""Build investor/pitch-deck.pdf out of investor/pitch-deck.html.

Every slide of the deck is written out as a standalone HTML document
(investor/print/slide-NN.html) — the same markup and the same stylesheet the
browser renders — and each of those documents is printed as exactly one page
of the merged PDF.

Page rules:

  * every page is A4 portrait (210 x 297 mm);
  * the slide is zoomed in until it fills the sheet, so no page carries a
    strip of empty paper;
  * a slide that still does not fit at the widest layout keeps the A4 width
    and gets a taller page — it is never split across two sheets.

The zoom knob is the CSS layout width the slide is rendered at: the sheet is
always 210 mm wide, so the narrower the layout, the bigger the slide prints.
The search walks that width down until either the slide fills the sheet, or
something that cannot reflow (a wide table, a chart) starts to be clipped.
Whatever slack is left after that is spread between the slide's blocks, so it
never pools into an empty strip at the bottom of the page.

Usage:
    pip install playwright pypdf
    python3 tools/build-pitch-deck-pdf.py

Chromium comes from playwright; set CHROME_PATH to use another binary.
"""

from __future__ import annotations

import functools
import http.server
import math
import os
import re
import socketserver
import sys
import threading
from io import BytesIO
from pathlib import Path

from playwright.sync_api import sync_playwright
from pypdf import PdfReader, PdfWriter

ROOT = Path(__file__).resolve().parent.parent
DECK_HTML = ROOT / "investor" / "pitch-deck.html"
PRINT_DIR = ROOT / "investor" / "print"
PDF_OUT = ROOT / "investor" / "pitch-deck.pdf"

MM_PER_PX = 25.4 / 96.0          # CSS px -> mm at the 96 dpi CSS reference
A4_W_MM, A4_H_MM = 210.0, 297.0
A4_W_PX = A4_W_MM / MM_PER_PX    # 793.7 — one sheet width in CSS px
A4_RATIO = A4_H_MM / A4_W_MM

# Widths (CSS px) a slide may be laid out at before it is blown up to the
# 210 mm of the sheet: the narrower the layout, the bigger the slide prints.
# The upper bound is how far we may zoom out to get a dense slide onto one
# sheet, the lower bound how far we may zoom in before the layout turns into a
# column of oversized type.
MIN_LAYOUT_W = 300
MAX_LAYOUT_W = 2400
SEARCH_STEP = 8                  # px resolution of the zoom search
FULL_ENOUGH = 0.985              # fill ratio that counts as "no empty strip"

# Chromium's print scale stops at 2.0 (210 mm / 400 px), so anything below
# that width is magnified the rest of the way with CSS zoom. The viewport —
# and with it the media queries — stays at 400 px there, the zoom only makes
# the layout box narrower.
MIN_VIEWPORT_W = 400

SLIDE_RE = re.compile(r'<section class="slide[^"]*" id="slide-(\d+)">.*?</section>', re.S)
NAV_RE = re.compile(
    r'data-slide="(\d+)"[^>]*>.*?<span class="deck-nav-title">(.*?)</span>', re.S
)

PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="robots" content="noindex, nofollow" />
  <base href="../" />
  <title>{title} &mdash; Pitch Deck &middot; Open Trader</title>
  <link rel="stylesheet" href="investor.css?v=25" />
  <link rel="stylesheet" href="print/print-page.css" />
</head>
<body>
  <!-- Generated by tools/build-pitch-deck-pdf.py from investor/pitch-deck.html.
       Edit the deck, not this file. -->
  <div class="inv-wrapper">
    <article class="inv-doc deck-doc">
      <main class="inv-doc-body">
        <div class="deck-stage">
{slide}
        </div>
      </main>
    </article>
  </div>
</body>
</html>
"""

# Height the slide would take if it were not stretched to the full sheet, plus
# whether anything is being cut off sideways at this width (a wide table or a
# chart inside an overflow container — those clip instead of reflowing).
MEASURE_JS = """(zoom) => {
  const probe = document.createElement('style');
  probe.textContent =
    'body{zoom:' + zoom + '}' +
    '.deck-doc .slide{min-height:0 !important;justify-content:flex-start !important}';
  document.head.appendChild(probe);

  const slide = document.querySelector('.slide');
  const height = Math.max(slide.getBoundingClientRect().height, slide.scrollHeight);

  let clipped = document.documentElement.scrollWidth > document.documentElement.clientWidth + 1;
  if (!clipped) {
    for (const el of slide.querySelectorAll('*')) {
      const overflowX = getComputedStyle(el).overflowX;
      if (overflowX !== 'visible' && el.scrollWidth > el.clientWidth + 1) { clipped = true; break; }
    }
  }

  probe.remove();
  return { height, clipped };
}"""


# ---------------------------------------------------------------- extraction


def unescape_title(raw: str) -> str:
    return (
        raw.replace("&amp;", "&")
        .replace("&middot;", "·")
        .replace("&mdash;", "—")
        .replace("&ndash;", "–")
        .replace("&rsquo;", "’")
        .strip()
    )


def write_slide_documents() -> list[Path]:
    """Split the deck into one standalone HTML document per slide."""
    deck = DECK_HTML.read_text(encoding="utf-8")
    titles = {int(n): unescape_title(t) for n, t in NAV_RE.findall(deck)}

    PRINT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in PRINT_DIR.glob("slide-*.html"):
        stale.unlink()

    paths: list[Path] = []
    for match in SLIDE_RE.finditer(deck):
        number = int(match.group(1))
        slide = match.group(0)
        # every sheet shows "the current slide" — investor.css only hangs the
        # entrance animation off .active, which print-page.css switches off
        slide = slide.replace('<section class="slide"', '<section class="slide active"', 1)
        title = titles.get(number, f"Slide {number}")
        path = PRINT_DIR / f"slide-{number:02d}.html"
        path.write_text(
            PAGE_TEMPLATE.format(title=f"{number:02d} &middot; {title}", slide=slide),
            encoding="utf-8",
        )
        paths.append(path)

    if not paths:
        sys.exit("no slides found in investor/pitch-deck.html")
    return paths


# ------------------------------------------------------------------- server


class QuietHandler(http.server.SimpleHTTPRequestHandler):
    def log_message(self, *args):  # noqa: D102 - silence the request log
        pass


def serve_root() -> socketserver.TCPServer:
    """Serve the repository over http so pages load exactly as deployed."""
    handler = functools.partial(QuietHandler, directory=str(ROOT))
    httpd = socketserver.TCPServer(("127.0.0.1", 0), handler)
    threading.Thread(target=httpd.serve_forever, daemon=True).start()
    return httpd


# ------------------------------------------------------------------- layout


def viewport_for(layout_w: int) -> tuple[int, float]:
    """Browser viewport and CSS zoom that lay a slide out at `layout_w`."""
    viewport_w = max(layout_w, MIN_VIEWPORT_W)
    return viewport_w, viewport_w / layout_w


def measure(page, layout_w: int, sheet_h_px: float) -> tuple[float, bool]:
    """Natural slide height (layout px) and horizontal-clipping flag."""
    viewport_w, zoom = viewport_for(layout_w)
    page.set_viewport_size({"width": viewport_w, "height": round(sheet_h_px * zoom)})
    page.wait_for_timeout(60)
    result = page.evaluate(MEASURE_JS, zoom)
    return float(result["height"]), bool(result["clipped"])


def probe(page, layout_w: int) -> tuple[float, bool]:
    """Fill ratio (slide height / sheet height) and clipping flag at a width."""
    sheet_h = layout_w * A4_RATIO
    height, clipped = measure(page, layout_w, sheet_h)
    return height / sheet_h, clipped


def choose_layout_width(page) -> tuple[int, float, bool]:
    """Narrowest layout — i.e. biggest zoom — the slide can be printed at.

    Bounded from below by two things: the slide must still fit the sheet
    vertically, and nothing may be cut off sideways. Returns the width, the
    fill ratio it gives, and whether the slide fits the sheet at all.
    """
    usable = lambda w: (lambda r: (r[0] <= 1.0 and not r[1]))(probe(page, w))

    if usable(MIN_LAYOUT_W):
        ratio, _ = probe(page, MIN_LAYOUT_W)
        return MIN_LAYOUT_W, ratio, True
    if not usable(MAX_LAYOUT_W):
        ratio, _ = probe(page, MAX_LAYOUT_W)
        return MAX_LAYOUT_W, ratio, False

    lo, hi = MIN_LAYOUT_W, MAX_LAYOUT_W  # lo unusable, hi usable
    while hi - lo > SEARCH_STEP:
        mid = (lo + hi) // 2
        if usable(mid):
            hi = mid
        else:
            lo = mid
    ratio, _ = probe(page, hi)
    return hi, ratio, True


def oversized_page_height(page, layout_w: int) -> float:
    """Sheet height (mm) for a slide that does not fit A4 even zoomed out.

    Keeps the A4 width and grows the sheet downwards until the whole slide is
    on it, re-measuring after each step because the slide's vertical paddings
    are viewport-height relative.
    """
    mm_per_layout_px = A4_W_MM / layout_w
    sheet_h = layout_w * A4_RATIO
    height_mm = A4_H_MM
    for _ in range(4):
        measured, _ = measure(page, layout_w, sheet_h)
        if measured <= sheet_h + 1:
            break
        height_mm = math.ceil(measured * mm_per_layout_px)
        sheet_h = height_mm / mm_per_layout_px
    return height_mm


# ------------------------------------------------------------------- render


def render(page, url: str) -> bytes:
    page.goto(url, wait_until="networkidle")
    page.emulate_media(media="print")
    page.evaluate("() => document.fonts.ready")

    layout_w, ratio, fits = choose_layout_width(page)
    height_mm = A4_H_MM if fits else oversized_page_height(page, layout_w)
    viewport_w, zoom = viewport_for(layout_w)
    if zoom != 1:
        page.add_style_tag(content=f":root {{ --print-zoom: {zoom:.4f}; }}")

    # Whatever slack is left after zooming in (a slide with a fixed-height
    # chart cannot always reach the bottom edge) is spread between the blocks
    # instead of pooling under the last one.
    if fits and ratio < FULL_ENOUGH:
        page.add_style_tag(content=".deck-doc .slide { justify-content: space-between; }")

    for attempt in range(6):
        pdf = page.pdf(
            width=f"{A4_W_MM}mm",
            height=f"{height_mm}mm",
            scale=A4_W_PX / viewport_w,  # 210 mm of paper == the whole viewport
            margin={"top": "0", "right": "0", "bottom": "0", "left": "0"},
            print_background=True,
            prefer_css_page_size=False,
        )
        if len(PdfReader(BytesIO(pdf)).pages) == 1:
            sheet = "A4" if abs(height_mm - A4_H_MM) < 0.5 else f"A4 width x {height_mm:.0f} mm"
            zoomed = "" if zoom == 1 else f", zoom {zoom:.2f}"
            print(f"    layout {layout_w}px{zoomed}, fill {ratio * 100:.0f}% -> {sheet}")
            return pdf

        # The measured layout and Chromium's paginated layout disagreed by a
        # hair: zoom out a notch, and once that is exhausted, grow the sheet.
        if height_mm <= A4_H_MM and layout_w < MAX_LAYOUT_W:
            layout_w = min(MAX_LAYOUT_W, round(layout_w * 1.04))
            viewport_w, zoom = viewport_for(layout_w)
            page.add_style_tag(content=f":root {{ --print-zoom: {zoom:.4f}; }}")
            page.set_viewport_size(
                {"width": viewport_w, "height": round(layout_w * A4_RATIO * zoom)}
            )
        else:
            height_mm = math.ceil(height_mm * 1.03)
        print(f"    retry {attempt + 1}: layout {layout_w}px, sheet {height_mm:.0f} mm")

    sys.exit(f"could not fit {url} on a single page")


def main() -> None:
    slides = write_slide_documents()
    print(f"wrote {len(slides)} slide documents to {PRINT_DIR.relative_to(ROOT)}/")

    httpd = serve_root()
    port = httpd.server_address[1]
    writer = PdfWriter()
    try:
        with sync_playwright() as pw:
            browser = pw.chromium.launch(executable_path=os.environ.get("CHROME_PATH"))
            for path in slides:
                rel = path.relative_to(ROOT).as_posix()
                print(f"  {rel}")
                page = browser.new_page()
                writer.append(PdfReader(BytesIO(render(page, f"http://127.0.0.1:{port}/{rel}"))))
                page.close()
            browser.close()
    finally:
        httpd.shutdown()

    with PDF_OUT.open("wb") as fh:
        writer.write(fh)
    print(f"{PDF_OUT.relative_to(ROOT)}: {len(writer.pages)} pages, "
          f"{PDF_OUT.stat().st_size / 1024:.0f} KB")


if __name__ == "__main__":
    main()
